"""init

Revision ID: b34e7c2a91e4
Revises: 
Create Date: 2026-06-17 23:22:28.161746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b34e7c2a91e4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_completions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(length=20), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_completions')),
    sa.UniqueConstraint('user_id', 'activity_type', 'activity_id', name='uq_completion')
    )
    op.create_index(op.f('ix_activity_completions_user_id'), 'activity_completions', ['user_id'], unique=False)
    op.create_table('block_completions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('xp_awarded', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_block_completions')),
    sa.UniqueConstraint('user_id', 'block_id', name='uq_block_completion')
    )
    op.create_index(op.f('ix_block_completions_block_id'), 'block_completions', ['block_id'], unique=False)
    op.create_index(op.f('ix_block_completions_user_id'), 'block_completions', ['user_id'], unique=False)
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('gating', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_courses'))
    )
    op.create_index(op.f('ix_courses_slug'), 'courses', ['slug'], unique=True)
    op.create_table('lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content_md', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lessons'))
    )
    op.create_index(op.f('ix_lessons_slug'), 'lessons', ['slug'], unique=True)
    op.create_table('level_thresholds',
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('required_xp', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('level', name=op.f('pk_level_thresholds'))
    )
    op.create_table('quiz_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quiz_attempts'))
    )
    op.create_index(op.f('ix_quiz_attempts_quiz_id'), 'quiz_attempts', ['quiz_id'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_user_id'), 'quiz_attempts', ['user_id'], unique=False)
    op.create_table('quizzes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('pass_threshold', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quizzes'))
    )
    op.create_index(op.f('ix_quizzes_slug'), 'quizzes', ['slug'], unique=True)
    op.create_table('trainer_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('cells', sa.JSON(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('per_cell_result', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trainer_submissions'))
    )
    op.create_index(op.f('ix_trainer_submissions_task_id'), 'trainer_submissions', ['task_id'], unique=False)
    op.create_index(op.f('ix_trainer_submissions_user_id'), 'trainer_submissions', ['user_id'], unique=False)
    op.create_table('trainer_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('instructions_md', sa.Text(), nullable=False),
    sa.Column('sheet', sa.JSON(), nullable=False),
    sa.Column('editable', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trainer_tasks'))
    )
    op.create_index(op.f('ix_trainer_tasks_slug'), 'trainer_tasks', ['slug'], unique=True)
    op.create_table('user_progress',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_xp', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user_progress'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('xp_reward', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_blocks_course_id_courses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blocks'))
    )
    op.create_index(op.f('ix_blocks_course_id'), 'blocks', ['course_id'], unique=False)
    op.create_index(op.f('ix_blocks_slug'), 'blocks', ['slug'], unique=False)
    op.create_table('quiz_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('correct', sa.JSON(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], name=op.f('fk_quiz_questions_quiz_id_quizzes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quiz_questions'))
    )
    op.create_index(op.f('ix_quiz_questions_quiz_id'), 'quiz_questions', ['quiz_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens'))
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('trainer_gradings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('rules', sa.JSON(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['trainer_tasks.id'], name=op.f('fk_trainer_gradings_task_id_trainer_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trainer_gradings'))
    )
    op.create_index(op.f('ix_trainer_gradings_task_id'), 'trainer_gradings', ['task_id'], unique=True)
    op.create_table('steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(length=20), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], name=op.f('fk_steps_block_id_blocks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_steps'))
    )
    op.create_index(op.f('ix_steps_block_id'), 'steps', ['block_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_steps_block_id'), table_name='steps')
    op.drop_table('steps')
    op.drop_index(op.f('ix_trainer_gradings_task_id'), table_name='trainer_gradings')
    op.drop_table('trainer_gradings')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_quiz_questions_quiz_id'), table_name='quiz_questions')
    op.drop_table('quiz_questions')
    op.drop_index(op.f('ix_blocks_slug'), table_name='blocks')
    op.drop_index(op.f('ix_blocks_course_id'), table_name='blocks')
    op.drop_table('blocks')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('user_progress')
    op.drop_index(op.f('ix_trainer_tasks_slug'), table_name='trainer_tasks')
    op.drop_table('trainer_tasks')
    op.drop_index(op.f('ix_trainer_submissions_user_id'), table_name='trainer_submissions')
    op.drop_index(op.f('ix_trainer_submissions_task_id'), table_name='trainer_submissions')
    op.drop_table('trainer_submissions')
    op.drop_index(op.f('ix_quizzes_slug'), table_name='quizzes')
    op.drop_table('quizzes')
    op.drop_index(op.f('ix_quiz_attempts_user_id'), table_name='quiz_attempts')
    op.drop_index(op.f('ix_quiz_attempts_quiz_id'), table_name='quiz_attempts')
    op.drop_table('quiz_attempts')
    op.drop_table('level_thresholds')
    op.drop_index(op.f('ix_lessons_slug'), table_name='lessons')
    op.drop_table('lessons')
    op.drop_index(op.f('ix_courses_slug'), table_name='courses')
    op.drop_table('courses')
    op.drop_index(op.f('ix_block_completions_user_id'), table_name='block_completions')
    op.drop_index(op.f('ix_block_completions_block_id'), table_name='block_completions')
    op.drop_table('block_completions')
    op.drop_index(op.f('ix_activity_completions_user_id'), table_name='activity_completions')
    op.drop_table('activity_completions')
    # ### end Alembic commands ###
